retaillite:
  company:
    name: RetailLite
    address:
      line1: ABC Road
      line2: Pune, Maharashtra 411001
    phone: +91 8459787658
    email: shivam@gmail.com
    website: https://demowebsite.demo
    gst-number: 27ABCDE1234F1Z5
    logo: classpath:static/logo.jpg


logging:
  level:
    root: INFO
    in.shivam.retaillite: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
spring:
  application:
    name: RetailLite
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      show-sql: true
      ddl-auto: none
  # Enable or disable Flyway completely (Default: true)
  flyway:
    enabled: true
    # Locations of migration scripts (Default: classpath:db/migration)
    locations: "classpath:db/migration"
    # Name of the table that will track schema history (Default: flyway_schema_history)
    table: "flyway_schema_history"
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 10MB
  docker:
    compose:
      enabled: false
server:
  servlet:
    context-path: /api/v1.0
app:
  security:
    jwt-secret-key: ${JWT_SECRET_KEY}
    token-expiration-in-minute: ${TOKEN_EXPIRATION_TIME_IN_MINUTE}

aws:
  region: ${AWS_REGION}
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  bucket-name: ${BUCKET_NAME}
  endpoint: http://localhost:4566
#todo:insert credentials
razorpay:
  key-id: ${RAZORPAY_KEY_ID}
  key-secret: ${RAZORPAY_KEY_SECRET}
  timeout: 10
  webhook-secret: ${RAZORPAY_WEBHOOK_SECRET}
payment:
  pending:
    payment-timeout: 15